# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 600))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../resources/images/cafe-luces.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.txt_correo = QtWidgets.QLineEdit(parent=Form)
        self.txt_correo.setGeometry(QtCore.QRect(310, 290, 280, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.txt_correo.setFont(font)
        self.txt_correo.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #F28705; /* Borde naranja */\n"
"    padding: 3px;\n"
"    color: #2C2C2C; /* Texto oscuro */\n"
"}\n"
"")
        self.txt_correo.setFrame(False)
        self.txt_correo.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_correo.setObjectName("txt_correo")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(310, 350, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(310, 270, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.box_form = QtWidgets.QWidget(parent=Form)
        self.box_form.setGeometry(QtCore.QRect(282, 79, 336, 441))
        self.box_form.setStyleSheet("QWidget {\n"
"    background-color: rgba(44, 44, 44, 200); /* Gris oscuro con opacidad */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    padding: 20px; /* Espaciado interno */\n"
"    border: 1px solid #F28705; /* Borde sutil naranja */\n"
"    box-shadow: 3px 3px 15px rgba(0, 0, 0, 100); /* Sombra para efecto flotante */\n"
"}\n"
"")
        self.box_form.setObjectName("box_form")
        self.button_login = QtWidgets.QPushButton(parent=self.box_form)
        self.button_login.setGeometry(QtCore.QRect(30, 370, 280, 34))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        self.button_login.setFont(font)
        self.button_login.setStyleSheet("QPushButton {\n"
"    background-color: #F28705;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 3px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A65A18; /* Oscurece en hover */\n"
"}")
        self.button_login.setObjectName("button_login")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(352, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.logoCafeteria = QtWidgets.QLabel(parent=Form)
        self.logoCafeteria.setGeometry(QtCore.QRect(389, 110, 101, 81))
        self.logoCafeteria.setText("")
        self.logoCafeteria.setPixmap(QtGui.QPixmap("../../../resources/images/logo-cafeteria.png"))
        self.logoCafeteria.setScaledContents(True)
        self.logoCafeteria.setObjectName("logoCafeteria")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(310, 370, 280, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.txt_password.setFont(font)
        self.txt_password.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #F28705; /* Borde naranja */\n"
"    padding: 3px;\n"
"    color: #2C2C2C; /* Texto oscuro */\n"
"}\n"
"")
        self.txt_password.setFrame(False)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label.raise_()
        self.box_form.raise_()
        self.txt_correo.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.logoCafeteria.raise_()
        self.txt_password.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Contraseña"))
        self.label_6.setText(_translate("Form", "Correo Electrónico"))
        self.button_login.setText(_translate("Form", "Ingresar"))
        self.label_7.setText(_translate("Form", "Iniciar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
