# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormMenu(object):
    def setupUi(self, FormMenu):
        FormMenu.setObjectName("FormMenu")
        FormMenu.resize(900, 600)
        self.label = QtWidgets.QLabel(parent=FormMenu)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 601))
        self.label.setStyleSheet("QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #1E1E1E, \n"
"                                stop:1 #2C2C2C);\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.logo_cafeteria = QtWidgets.QLabel(parent=FormMenu)
        self.logo_cafeteria.setGeometry(QtCore.QRect(390, 30, 101, 81))
        self.logo_cafeteria.setText("")
        self.logo_cafeteria.setPixmap(QtGui.QPixmap("../../../resources/images/logo-cafeteria.png"))
        self.logo_cafeteria.setScaledContents(True)
        self.logo_cafeteria.setObjectName("logo_cafeteria")
        self.cerrar_sesion = QtWidgets.QPushButton(parent=FormMenu)
        self.cerrar_sesion.setGeometry(QtCore.QRect(790, 490, 51, 51))
        self.cerrar_sesion.setStyleSheet("QPushButton {\n"
"    background-color: transparent; \n"
"    border: none; \n"
"    border-radius: 12px;\n"
"    padding: 8px 12px;\n"
"    transition: all 0.3s ease-in-out;\n"
"    cursor: pointer; /* Indica que es clickeable */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(209, 122, 34,250); /* Naranja vibrante */\n"
"    border: none; /* Borde crema */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    transform: scale(0.90); /* Pequeña reducción de tamaño para efecto táctil */\n"
"}\n"
"")
        self.cerrar_sesion.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/images/cerrar-sesion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cerrar_sesion.setIcon(icon)
        self.cerrar_sesion.setIconSize(QtCore.QSize(50, 50))
        self.cerrar_sesion.setObjectName("cerrar_sesion")
        self.widget = QtWidgets.QWidget(parent=FormMenu)
        self.widget.setGeometry(QtCore.QRect(178, 138, 541, 181))
        self.widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout.setSpacing(32)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_registrar_ventas = QtWidgets.QToolButton(parent=self.widget)
        self.button_registrar_ventas.setMinimumSize(QtCore.QSize(151, 151))
        self.button_registrar_ventas.setMaximumSize(QtCore.QSize(151, 151))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.button_registrar_ventas.setFont(font)
        self.button_registrar_ventas.setStyleSheet("QToolButton {\n"
"    background-color: #2C2C2C; /* Gris oscuro */\n"
"    border: 2px solid #D17A22; /* Borde naranja */\n"
"    border-radius: 12px;\n"
"    color: #F2E8CF;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 7px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #D17A22; /* Se vuelve naranja */\n"
"    color: #1E1E1E; /* Texto oscuro para contraste */\n"
"    border: 2px solid #F2E8CF; /* Borde en crema */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #A65A18; /* Naranja más oscuro */\n"
"    border: 2px solid #F2E8CF;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../resources/images/registro-ventas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_registrar_ventas.setIcon(icon1)
        self.button_registrar_ventas.setIconSize(QtCore.QSize(80, 80))
        self.button_registrar_ventas.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_registrar_ventas.setObjectName("button_registrar_ventas")
        self.horizontalLayout.addWidget(self.button_registrar_ventas)
        self.button_gestionar_stock = QtWidgets.QToolButton(parent=self.widget)
        self.button_gestionar_stock.setMinimumSize(QtCore.QSize(151, 151))
        self.button_gestionar_stock.setMaximumSize(QtCore.QSize(151, 151))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.button_gestionar_stock.setFont(font)
        self.button_gestionar_stock.setStyleSheet("QToolButton {\n"
"    background-color: #2C2C2C; /* Gris oscuro */\n"
"    border: 2px solid #D17A22; /* Borde naranja */\n"
"    border-radius: 12px;\n"
"    color: #F2E8CF;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 7px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #D17A22; /* Se vuelve naranja */\n"
"    color: #1E1E1E; /* Texto oscuro para contraste */\n"
"    border: 2px solid #F2E8CF; /* Borde en crema */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #A65A18; /* Naranja más oscuro */\n"
"    border: 2px solid #F2E8CF;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../resources/images/gestion-stock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_gestionar_stock.setIcon(icon2)
        self.button_gestionar_stock.setIconSize(QtCore.QSize(80, 80))
        self.button_gestionar_stock.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_gestionar_stock.setObjectName("button_gestionar_stock")
        self.horizontalLayout.addWidget(self.button_gestionar_stock)
        self.button_reportes_ventas = QtWidgets.QToolButton(parent=self.widget)
        self.button_reportes_ventas.setMinimumSize(QtCore.QSize(151, 151))
        self.button_reportes_ventas.setMaximumSize(QtCore.QSize(151, 151))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.button_reportes_ventas.setFont(font)
        self.button_reportes_ventas.setStyleSheet("QToolButton {\n"
"    background-color: #2C2C2C; /* Gris oscuro */\n"
"    border: 2px solid #D17A22; /* Borde naranja */\n"
"    border-radius: 12px;\n"
"    color: #F2E8CF;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 7px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #D17A22; /* Se vuelve naranja */\n"
"    color: #1E1E1E; /* Texto oscuro para contraste */\n"
"    border: 2px solid #F2E8CF; /* Borde en crema */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #A65A18; /* Naranja más oscuro */\n"
"    border: 2px solid #F2E8CF;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../resources/images/reporte-ventas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_reportes_ventas.setIcon(icon3)
        self.button_reportes_ventas.setIconSize(QtCore.QSize(80, 80))
        self.button_reportes_ventas.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_reportes_ventas.setObjectName("button_reportes_ventas")
        self.horizontalLayout.addWidget(self.button_reportes_ventas)
        self.widget_2 = QtWidgets.QWidget(parent=FormMenu)
        self.widget_2.setGeometry(QtCore.QRect(260, 320, 381, 181))
        self.widget_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_2.setSpacing(24)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_tendencias = QtWidgets.QToolButton(parent=self.widget_2)
        self.button_tendencias.setMinimumSize(QtCore.QSize(151, 151))
        self.button_tendencias.setMaximumSize(QtCore.QSize(151, 151))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.button_tendencias.setFont(font)
        self.button_tendencias.setStyleSheet("QToolButton {\n"
"    background-color: #2C2C2C; /* Gris oscuro */\n"
"    border: 2px solid #D17A22; /* Borde naranja */\n"
"    border-radius: 12px;\n"
"    color: #F2E8CF;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 7px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #D17A22; /* Se vuelve naranja */\n"
"    color: #1E1E1E; /* Texto oscuro para contraste */\n"
"    border: 2px solid #F2E8CF; /* Borde en crema */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #A65A18; /* Naranja más oscuro */\n"
"    border: 2px solid #F2E8CF;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../resources/images/tendencia-ventas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_tendencias.setIcon(icon4)
        self.button_tendencias.setIconSize(QtCore.QSize(80, 80))
        self.button_tendencias.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_tendencias.setObjectName("button_tendencias")
        self.horizontalLayout_2.addWidget(self.button_tendencias)
        self.button_prediccion = QtWidgets.QToolButton(parent=self.widget_2)
        self.button_prediccion.setMinimumSize(QtCore.QSize(151, 151))
        self.button_prediccion.setMaximumSize(QtCore.QSize(151, 151))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.button_prediccion.setFont(font)
        self.button_prediccion.setStyleSheet("QToolButton {\n"
"    background-color: #2C2C2C; /* Gris oscuro */\n"
"    border: 2px solid #D17A22; /* Borde naranja */\n"
"    border-radius: 12px;\n"
"    color: #F2E8CF;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 3px;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #D17A22; /* Se vuelve naranja */\n"
"    color: #1E1E1E; /* Texto oscuro para contraste */\n"
"    border: 2px solid #F2E8CF; /* Borde en crema */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #A65A18; /* Naranja más oscuro */\n"
"    border: 2px solid #F2E8CF;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../resources/images/prediccion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_prediccion.setIcon(icon5)
        self.button_prediccion.setIconSize(QtCore.QSize(80, 80))
        self.button_prediccion.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_prediccion.setObjectName("button_prediccion")
        self.horizontalLayout_2.addWidget(self.button_prediccion)

        self.retranslateUi(FormMenu)
        QtCore.QMetaObject.connectSlotsByName(FormMenu)

    def retranslateUi(self, FormMenu):
        _translate = QtCore.QCoreApplication.translate
        FormMenu.setWindowTitle(_translate("FormMenu", "Form"))
        self.button_registrar_ventas.setText(_translate("FormMenu", "Registrar Ventas"))
        self.button_gestionar_stock.setText(_translate("FormMenu", "Gestionar Stock"))
        self.button_reportes_ventas.setText(_translate("FormMenu", "Reportes de Ventas"))
        self.button_tendencias.setText(_translate("FormMenu", "Tendencia de\n"
"Ventas"))
        self.button_prediccion.setText(_translate("FormMenu", "Predicción de\n"
" Demanda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMenu = QtWidgets.QWidget()
    ui = Ui_FormMenu()
    ui.setupUi(FormMenu)
    FormMenu.show()
    sys.exit(app.exec())
